sudo: false
language: rust

rust:
    - stable
    - beta
    - nightly

cache: cargo

matrix:
    allow_failures:
        - rust: nightly

before_install:
    - export TZ=America/New_York

before_script:
    - |
        pip install 'travis-cargo' --user && export PATH=$HOME/.local/bin:$PATH

script:
    - travis-cargo -q build
    - travis-cargo -q test
